[release_intel]
AMD = "0"
AVX2 = "0"
BOOTARGS = 'keepsyms=1 -lilubetaall '
DEBUG = "0"
DESCRIPTION = "Release Intel"
HIDEAUXILLARY = "true"
RESOLUTION = "1440x900@32"
TIMEOUT = "5"

[release_amd]
AMD = "1"
AVX2 = "0"
BOOTARGS = 'keepsyms=1 -lilubetaall '
DEBUG = "0"
DESCRIPTION = "Release AMD"
HIDEAUXILLARY = "true"
RESOLUTION = "1440x900@32"
TIMEOUT = "5"

[debug_intel]
AMD = "0"
AVX2 = "0"
BOOTARGS = '-v keepsyms=1 serial=1 -no_panic_dialog -lilubetaall -liludbgall'
DEBUG = "1"
DESCRIPTION = "Debug Intel"
HIDEAUXILLARY = "false"
RESOLUTION = "1440x900@32"
TIMEOUT = "10"

[debug_amd]
AMD = "1"
AVX2 = "0"
BOOTARGS = '-v keepsyms=1 serial=1 -no_panic_dialog -lilubetaall -liludbgall'
DEBUG = "1"
DESCRIPTION = "Debug AMD"
HIDEAUXILLARY = "false"
RESOLUTION = "1440x900@32"
TIMEOUT = "10"
