[intel-release]
AMD = "0"
AVX2 = "0"
BOOTARGS = 'keepsyms=1 -lilubetaall '
DEBUG = "0"
DESCRIPTION = "Release Intel"
HIDEAUXILLARY = "true"
RESOLUTION = "1440x900@32"
TIMEOUT = "5"

[amd-release]
AMD = "1"
AVX2 = "0"
BOOTARGS = 'keepsyms=1 -lilubetaall '
DEBUG = "0"
DESCRIPTION = "Release AMD"
HIDEAUXILLARY = "true"
RESOLUTION = "1440x900@32"
TIMEOUT = "5"

[intel-verbose]
AMD = "0"
AVX2 = "0"
BOOTARGS = '-v keepsyms=1 serial=1 -no_panic_dialog -lilubetaall -liludbgall'
DEBUG = "0"
DESCRIPTION = "Verbose Intel"
HIDEAUXILLARY = "true"
RESOLUTION = "1440x900@32"
TIMEOUT = "5"

[amd-verbose]
AMD = "1"
AVX2 = "0"
BOOTARGS = '-v keepsyms=1 serial=1 -no_panic_dialog -lilubetaall -liludbgall'
DEBUG = "0"
DESCRIPTION = "Verbose AMD"
HIDEAUXILLARY = "true"
RESOLUTION = "1440x900@32"
TIMEOUT = "5"

[intel-debug]
AMD = "0"
AVX2 = "0"
BOOTARGS = '-v keepsyms=1 serial=1 -no_panic_dialog -lilubetaall -liludbgall'
DEBUG = "1"
DESCRIPTION = "Debug Intel"
HIDEAUXILLARY = "false"
RESOLUTION = "1440x900@32"
TIMEOUT = "0"

[amd-debug]
AMD = "1"
AVX2 = "0"
BOOTARGS = '-v keepsyms=1 serial=1 -no_panic_dialog -lilubetaall -liludbgall'
DEBUG = "1"
DESCRIPTION = "Debug AMD"
HIDEAUXILLARY = "false"
RESOLUTION = "1440x900@32"
TIMEOUT = "0"
