[intel-release]
AVX2 = "0"
BOOTARGS = "keepsyms=1 -lilubetaall"
CSRCONFIG = "AAAAAA=="
DEBUG = "0"
DESCRIPTION = "Release Intel"
HIDEAUXILLARY = "true"
RESOLUTION = "1440x900@32"
SERIAL = "0"
TIMEOUT = "5"

[intel-verbose]
AVX2 = "0"
BOOTARGS = "keepsyms=1 -lilubetaall -v serial=5"
CSRCONFIG = "AAAAAA=="
DEBUG = "0"
DESCRIPTION = "Verbose Intel"
HIDEAUXILLARY = "true"
SERIAL = "1"
RESOLUTION = "1440x900@32"
TIMEOUT = "5"

[intel-debug]
AVX2 = "0"
BOOTARGS = "keepsyms=1 -lilubetaall -v serial=5 debug=2 -no_panic_dialog -liludbgall -topo -cpuid"
CSRCONFIG = "AAAAAA=="
DEBUG = "1"
DESCRIPTION = "Debug Intel"
HIDEAUXILLARY = "false"
RESOLUTION = "1440x900@32"
SERIAL = "1"
TIMEOUT = "0"

[intel-kdk]
AVX2 = "0"
BOOTARGS = "keepsyms=1 -lilubetaall -v serial=5 debug=2 -no_panic_dialog -liludbgall -topo -cpuid kcsuffix=development"
CSRCONFIG = "fwgAAA=="
DEBUG = "1"
DESCRIPTION = "KDK Intel"
HIDEAUXILLARY = "false"
RESOLUTION = "1440x900@32"
SERIAL = "1"
TIMEOUT = "0"
