#TODO: Add ability to specify Mac system in TOML
#TODO: Add CPU count and core to AMD patches

#
# Intel CPU Settings
#
[intel-release]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS Intel Release'
DMG = 'release'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '5'
VMX = 'release'

[intel-verbose]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -v serial=1'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS Intel Verbose'
DMG = 'release'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
SERIAL = 'TRUE'
RESOLUTION = '1440x900@32'
TIMEOUT = '5'
VMX = 'release'

[intel-debug]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid'
CSRCONFIG = 'AAAAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS Intel Debug'
DMG = 'debug'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'
VMX = 'debug'

[intel-kdk]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid kcsuffix=development'
CSRCONFIG = 'fwgAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS Intel KDK'
DMG = 'debug'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'
VMX = 'debug'

#
# AMD CPU Settings
#
[amd-release]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS AMD Release'
DMG = 'release'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '5'
VMX = 'release'

[amd-verbose]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -v serial=1'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS AMD Verbose'
DMG = 'release'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
SERIAL = 'TRUE'
RESOLUTION = '1440x900@32'
TIMEOUT = '5'
VMX = 'release'

[amd-debug]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid avx512=0 cwad'
CSRCONFIG = 'AAAAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS AMD Debug'
DMG = 'debug'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'
VMX = 'debug'

[amd-kdk]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid avx512=0 cwad kcsuffix=development'
CSRCONFIG = 'fwgAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS AMD KDK'
DMG = 'debug'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'
VMX = 'debug'
