#TODO: Add ability to specify Mac system in TOML

[intel-release]
BUILD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macos Intel Release'
ETHERNET_DEVICE = 'e1000e'
FILES = 'release-base'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '5'
VMX = 'release'

[intel-verbose]
BUILD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -v serial=5'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macos Intel Verbose'
ETHERNET_DEVICE = 'e1000e'
FILES = 'release-base'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
SERIAL = 'TRUE'
RESOLUTION = '1440x900@32'
TIMEOUT = '5'
VMX = 'release'

# These are not normally built and are for debugging only
[intel-debug]
BUILD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -v serial=5 debug=2 -no_panic_dialog -liludbgall -topo -cpuid'
CSRCONFIG = 'AAAAAA=='
DEBUG = '1'
DESCRIPTION = 'macos Intel Debug'
ETHERNET_DEVICE = 'e1000e'
FILES = 'debug-base'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'
VMX = 'debug'

[intel-kdk]
BUILD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -v serial=5 debug=2 -no_panic_dialog -liludbgall -topo -cpuid kcsuffix=development'
CSRCONFIG = 'fwgAAA=='
DEBUG = '1'
DESCRIPTION = 'macos Intel KDK'
ETHERNET_DEVICE = 'e1000e'
FILES = 'debug-base'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'
VMX = 'debug'
