# SPDX-FileCopyrightText: © 2023-25 David Parsons
# SPDX-License-Identifier: MIT

#
# Intel CPU Settings
#
[intel]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS Intel Release OC'
DMG = 'release'
RESOLUTION = '1440x900@32'
TIMEOUT = '5'

[intel-debug]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check -no_panic_dialog vmhState=disabled -liludbgall'
CSRCONFIG = 'AAAAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS Intel Debug OC'
DMG = 'debug'
RESOLUTION = '1440x900@32'
TIMEOUT = '0'

#
# AMD CPU Settings
#
[amd]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS AMD Release OC'
DMG = 'release'
RESOLUTION = '1440x900@32'
TIMEOUT = '0'

[amd-debug]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check -no_panic_dialog vmhState=disabled -liludbgall'
CSRCONFIG = 'AAAAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS AMD Debug OC'
DMG = 'debug'
RESOLUTION = '1440x900@32'
TIMEOUT = '0'
