# SPDX-FileCopyrightText: © 2023-25 David Parsons
# SPDX-License-Identifier: MIT

#
# Intel CPU Settings
#
[intel]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS Intel'
DMG = 'release'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '0'

[intel-verbose]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -v -no_panic_dialog'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS Intel Verbose'
DMG = 'release'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '0'

[intel-trace]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -v serial=1 -no_panic_dialog'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS Intel Trace'
DMG = 'release'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'

[intel-debug]
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall'
CSRCONFIG = 'AAAAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS Intel Debug'
DMG = 'debug'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'

[intel-kdk]
BUILD = '0'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid kcsuffix=development'
CSRCONFIG = 'fwgAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS Intel KDK'
DMG = 'debug'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'

#
# AMD CPU Settings
#
[amd]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS AMD'
DMG = 'release'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '0'

[amd-verbose]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -v -no_panic_dialog'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS AMD Verbose'
DMG = 'release'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '0'

[amd-trace]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -v serial=1 -no_panic_dialog'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS AMD Trace'
DMG = 'release'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '5'

[amd-debug]
BUILD = '1'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall avx512=0 cwad'
CSRCONFIG = 'AAAAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS AMD Debug'
DMG = 'debug'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'

[amd-kdk]
BUILD = '0'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid avx512=0 cwad kcsuffix=development'
CSRCONFIG = 'fwgAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS AMD KDK'
DMG = 'debug'
HIDEAUXILLARY = 'false'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'
