[intel-release]
BUILD = '1'
DISPLAYNAME = 'macOS Intel Release Template'
SERIAL = '0'

[intel-verbose]
BUILD = '1'
DISPLAYNAME = 'macOS Intel Verbose Template'
SERIAL = '1'

# These are not normally built and are for debugging only
[intel-debug]
BUILD = '0'
DISPLAYNAME = 'macOS Intel Debug Template'
SERIAL = '1'

[intel-kdk]
BUILD = '0'
DISPLAYNAME = 'macOS Intel KDK Template'
SERIAL = '1'
