# SPDX-FileCopyrightText: © 2023-25 David Parsons
# SPDX-License-Identifier: MIT

#
# Intel CPU Settings
#
[intel]
BUILD = '1'
AMD = '0'
DESCRIPTION = 'macOS Intel'

#
# AMD CPU Settings
#
[amd]
BUILD = '1'
AMD = '1'
DESCRIPTION = 'macOS AMD'
