[intel_generic]
AMD = "0"
AVX1 = "1"
AVX2 = "1"
RDRAND = "1"
DISPLAYNAME = 'macOS Intel'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[intel_macos_10_15]
AMD = "0"
AVX1 = "1"
AVX2 = "0"
RDRAND = "1"
DISPLAYNAME = 'macOS 10.15 Catalina'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin19-64'

[intel_macos_11]
AMD = "0"
AVX1 = "1"
AVX2 = "0"
RDRAND = "1"
DISPLAYNAME = 'macOS 11 Big Sur'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[intel_macos_12]
AMD = "0"
AVX1 = "1"
AVX2 = "0"
RDRAND = "1"
DISPLAYNAME = 'macOS 12 Monterey'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[intel_macos_13]
AMD = "0"
AVX1 = "1"
AVX2 = "0"
RDRAND = "1"
DISPLAYNAME = 'macOS 13 Ventura'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[amd_generic]
AMD = "1"
AVX1 = "1"
AVX2 = "1"
RDRAND = "1"
DISPLAYNAME = 'macOS AMD'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[amd_macos_10_15]
AMD = "1"
AVX1 = "1"
AVX2 = "0"
RDRAND = "1"
DISPLAYNAME = 'macOS 10.15 Catalina'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin19-64'

[amd_macos_11]
AMD = "1"
AVX1 = "1"
AVX2 = "0"
RDRAND = "1"
DISPLAYNAME = 'macOS 11 Big Sur'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[amd_macos_12]
AMD = "1"
AVX1 = "1"
AVX2 = "0"
RDRAND = "1"
DISPLAYNAME = 'macOS 12 Monterey'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[amd_macos_13]
AMD = "1"
AVX1 = "1"
AVX2 = "0"
RDRAND = "1"
DISPLAYNAME = 'macOS 13 Ventura'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
