[intel_macos_10_15]
AMD = "0"
AVX1 = "0"
AVX2 = "0"
RDRAND = "0"
DISPLAYNAME = 'maOS 10.15 Catalina'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin19-64'

[intel_macos_11]
AMD = "0"
AVX1 = "0"
AVX2 = "0"
RDRAND = "0"
DISPLAYNAME = 'maOS 11 Big Sur'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[intel_macos_12]
AMD = "0"
AVX1 = "0"
AVX2 = "0"
RDRAND = "0"
DISPLAYNAME = 'maOS 12 Monterey'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[intel_macos_13]
AMD = "0"
AVX1 = "0"
AVX2 = "0"
RDRAND = "0"
DISPLAYNAME = 'macOS 13 Ventura'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[amd_macos_10_15]
AMD = "1"
AVX1 = "0"
AVX2 = "0"
RDRAND = "0"
DISPLAYNAME = 'maOS 10.15 Catalina'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin19-64'

[amd_macos_11]
AMD = "1"
AVX1 = "0"
AVX2 = "0"
RDRAND = "0"
DISPLAYNAME = 'maOS 11 Big Sur'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[amd_macos_12]
AMD = "1"
AVX1 = "0"
AVX2 = "0"
RDRAND = "0"
DISPLAYNAME = 'maOS 12 Monterey'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'

[amd_macos_13]
AMD = "1"
AVX1 = "0"
AVX2 = "0"
RDRAND = "0"
DISPLAYNAME = 'macOS 13 Ventura'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
