[intel-release]
BUILD = '1'
DISPLAYNAME = 'macOS Intel Release Template'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
SERIAL = 'FALSE'
VMX = 'release'

[intel-verbose]
BUILD = '1'
DISPLAYNAME = 'macOS Intel Verbose Template'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
SERIAL = 'TRUE'
VMX = 'debug'

# These are not normally built and are for debugging only
[intel-debug]
BUILD = '0'
DISPLAYNAME = 'macOS Intel Debug Template'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
SERIAL = 'TRUE'
VMX = 'debug'

[intel-kdk]
BUILD = '0'
DISPLAYNAME = 'macOS Intel KDK Template'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
SERIAL = 'TRUE'
VMX = 'debug'
