VARIANT = 'amd-installer'
BUILD = '0'
AMD = '1'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS AMD Installer'
DMG = 'release'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
RECOVERY = '1'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '0'
VMX = 'release'