VARIANT = 'intel-default'
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS Intel'
DMG = 'release'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
RECOVERY = '0'
RESOLUTION = '1440x900@32'
SERIAL = 'FALSE'
TIMEOUT = '5'
VMX = 'release'