VARIANT = 'intel-debug'
BUILD = '0'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid'
CSRCONFIG = 'AAAAAA=='
DEBUG = '1'
DESCRIPTION = 'macOS Intel Debug'
DMG = 'debug'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'false'
RECOVERY = '0'
RESOLUTION = '1440x900@32'
SERIAL = 'TRUE'
TIMEOUT = '0'
VMX = 'debug'