VARIANT = 'intel-verbose'
BUILD = '1'
AMD = '0'
BOOTARGS = 'keepsyms=1 -lilubetaall -no_compat_check -v serial=1'
CSRCONFIG = 'AAAAAA=='
DEBUG = '0'
DESCRIPTION = 'macOS Intel Verbose'
DMG = 'release'
ETHERNET_DEVICE = 'e1000e'
GUESTOS = 'darwin20-64'
HIDEAUXILLARY = 'true'
SERIAL = 'TRUE'
RECOVERY = '0'
RESOLUTION = '1440x900@32'
TIMEOUT = '0'
VMX = 'release'