[intel]
default = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled'
stealth = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=enabled'
verbose = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled -v'
trace = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled -v serial=1'
debug = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled -v serial=1 debug=2'
kdk = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid kcsuffix=development'

[amd]
default = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled'
stealth = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=enabled'
verbose = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled -v'
trace = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled -v serial=1'
debug = 'keepsyms=1 -lilubetaall -no_compat_check -no_panic_dialog vmhState=disabled -v serial=1 debug=2'
kdk = 'keepsyms=1 -lilubetaall -v -no_compat_check serial=1 debug=2 -no_panic_dialog -liludbgall -topo -cpuid kcsuffix=development'